// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/vx-labs/vespiary/vespiary/api"
)

type CreateApplicationOutput struct {
	Application *api.Application `json:"application"`
	Success     bool             `json:"success"`
}

type CreateApplicationProfileOutput struct {
	ApplicationProfile *api.ApplicationProfile `json:"applicationProfile"`
	Success            bool                    `json:"success"`
}
